// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxDkzKNTZzvZjpXozhNFDI-pzrhfOtIpc',
    appId: '1:507256928706:web:5ebe95f4b4fb84d6bfbe5b',
    messagingSenderId: '507256928706',
    projectId: 'dartstarter-project',
    authDomain: 'dartstarter-project.firebaseapp.com',
    storageBucket: 'dartstarter-project.appspot.com',
    measurementId: 'G-J4DC0VH06G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrEosM6w7J4w86GASHWIo2pMWKCsTXN1g',
    appId: '1:507256928706:android:bc04c60107bddfb6bfbe5b',
    messagingSenderId: '507256928706',
    projectId: 'dartstarter-project',
    storageBucket: 'dartstarter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCduQpCHQ7oiYin-el3yUzQAcrN9IoU-nA',
    appId: '1:507256928706:ios:0b3c282bf75674b0bfbe5b',
    messagingSenderId: '507256928706',
    projectId: 'dartstarter-project',
    storageBucket: 'dartstarter-project.appspot.com',
    iosClientId: '507256928706-83og2pf54sglea7it5dfvkeul8qccbi7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dartstarter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCduQpCHQ7oiYin-el3yUzQAcrN9IoU-nA',
    appId: '1:507256928706:ios:7d06a2b2dfe5b3c6bfbe5b',
    messagingSenderId: '507256928706',
    projectId: 'dartstarter-project',
    storageBucket: 'dartstarter-project.appspot.com',
    iosClientId: '507256928706-e6m4hol5fl3jmg4b3ond2qa27koldir4.apps.googleusercontent.com',
    iosBundleId: 'com.example.dartstarter.RunnerTests',
  );
}
